### ISSUE TITLE
This Camera works.

### ISSUE THREAD

**Issue by TheDukeSr** [rroller/dahua#10]
Hi,

Did not know where to put this info..
Just wanted to let you know that my Dahua IP cam also works.

Thnx for this Dahua integration in Hass.

Camera Type: **IPC-HDW4233C-A**

Not all functions yet tested, but overall it seems ok and no problems adding it to Hass.

Grtz Duke.

**Comment by rroller** [comment]
Thanks! Will update the readme with this info.
