### ISSUE TITLE
Question: Possible to use configuration.yaml instead of UI

### ISSUE THREAD

**Issue by laurensV** [rroller/dahua#100]
In the instructions in the README it shows that you can setup the camera through the UI, which stores config settings like the password in a file in the.storage folder. Is it also possible to use configuration.yaml to configure the camera instead of the UI? There I would be able to move the password to secrets.yaml and commit the config (without the password) to git for version control. Or would there be a way to hide/move the password from the JSON config in the .storage folder? Thanks!

**Comment by rroller** [comment]
Right now this is not possible and it would require more work to support the yaml config. I'm not going to have time to support this right now. I might reopen this in the future if I get the time to add support for yaml config.
