### ISSUE TITLE
Use Integration for Events only and Disable camera streams.

### ISSUE THREAD

**Issue by bryeartem** [rroller/dahua#102]
**Is your feature request related to a problem? Please describe.**
I already use Frigate which is how I bring in my camera streams.  I currently have an external method of getting Amcrest events from my NVR using MQTT and https://github.com/psyciknz/CameraEvents  Which I then have to manually create the sensors for in HA.
**Describe the solution you'd like**
I was hoping I could use this component to automatically connect to my NVR and create all available Event Sensors, VideoBlind, VideoMotion, CrossRegionDetection, Etc for all of my connected cameras, without requiring the external container from HA (It works super well but just wanted everything HA related in HA)
**Describe alternatives you've considered**
There really haven't been any viable alternatives as any Amcrest integrations I have looked at over the years never support NVRs, only direct connections to each camera.

**Additional context**
I believe the stream component has been improved where integrating camera streams isn't that CPU intensive anymore if you aren't watching them at the moment, but with them all already coming through Frigate I didn't want that extra load of duplicate camera streams. 
Just a hope... not a big deal as I mentioned I have a working solution for now but was hoping for the sensor creation more than anything.

**Comment by Margriko** [comment]
Maybe I am missing something but you can go to:
'Configuration' -> 'Integrations' -> under Dahua integration select your NVR -> 'Configure' -> deselect 'Camera enabled'

**Comment by bryeartem** [comment]
Nope you aren’t missing anything… I relied on the info that it wasn’t possible from asking someone else in a forum post without actually looking myself… I’ll delete
