### ISSUE TITLE
Get Snapshot

### ISSUE THREAD

**Issue by USAFPride** [rroller/dahua#105]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add ability to request screenshot within the integration similar to the VTO button push: `dahua.vto_open_door`
The following URL should work for most cameras with a request of `dahua.get_screenshot`
`http://login:password@cameraIP/cgi-bin/snapshot.cgi`

**Comment by rroller** [comment]
This is already supported with `camera.snapshot`

Here's an example:

![image](https://user-images.githubusercontent.com/445655/147420197-6e9f7ba2-56c8-4e70-8493-beb0e2c0cd12.png)

**Comment by si458** [comment]
@rroller sorry to add to this but the snapshot feature doesnt seem to work with multiple streams?
i ask for snapshot of sub (low quality) and it saves no problem
i ask for snapshot of main (high quality) and it still saves a low quality snapshot?
any suggestions?

**Comment by GaryOkie** [comment]
By chance are you referring to the AD410 doorbell?    If so, the factory configuration for its main (substream 0) snapshot resolution is not 2K HD, but lower quality.   It can be changed via the API.

For any Dahua/Amcrest camera, you can confirm the resolution of the main stream snapshot via:   
`<ip_address>/cgi-bin/configManager.cgi?action=getConfig&name=Encode[0].SnapFormat[0]`

**Comment by si458** [comment]
> By chance are you referring to the AD410 doorbell?    If so, the factory configuration for its main (substream 0) snapshot resolution is not 2K HD, but lower quality.   It can be changed via the API.
> 
> For any Dahua/Amcrest camera, you can confirm the resolution of the main stream snapshot via:   
> `<ip_address>/cgi-bin/configManager.cgi?action=getConfig&name=Encode[0].SnapFormat[0]`

No I'm referring to a normal DVR unit,
but I will check the units config for snapshot settings
Thanks for the suggestion!
