### ISSUE TITLE
Amcrest camera

### ISSUE THREAD

**Issue by kiwijunglist** [rroller/dahua#106]
Hi

Your integration partially works with my Amcrest camera.

Amcrest ProHD 1080P IP2M-841B

https://www.amazon.com/dp/B0145OQTPG

Software VersionV2.420.AC00.18.R, Build Date: 2019-08-03
WEB Version3.2.1.619604
ONVIF Version16.12(V2.4.1.513183)
S/NAMC000647ADA9BA3EA

What works:
Have a preview of the camera feed that updates every few seconds.

What doesn't work:
When I click on the camera and try to load the live stream it doesn't work (Yes I have added ffmpeg to configuration.yaml).

This is the error in the home assistant log file
```
2021-10-25 23:54:08 ERROR (stream_worker) [libav.rtsp] method OPTIONS failed: 404 Not Found
2021-10-25 23:54:08 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://****:****@192.168.1.90:554/cam/realmonitor?channel=0&subtype=0
```

If I want to view my camera in VLC the following work

```
rtsp://login.passwd@192.168.1.90:80/cam/realmonitor?channel=1&subtype=0
rtsp://login.passwd@192.168.1.90:554/cam/realmonitor?channel=1&subtype=0
```

But the following doesn't work:
```
..... channel=0  ....
```

So the problem is that it is trying to load channel=0

**Comment by rroller** [comment]
Does the audio/movement detection and switch work when on channel 0?

**Comment by kiwijunglist** [comment]
Hi merry Xmas. I can't remember I will investigate when return from holiday Inn a few weeks.

**Comment by rroller** [comment]
Thanks. I'm going to resolve this now to help clear the queue since I think this is working. Please reopen if it doesn't work.

**Comment by kzaoaai** [comment]
@rroller It's been a while but I just ran into this. Channel 0 allows for motion/sound detection, but no video. Channel 1 allows for video but no motion/sound detection.

**Comment by kiwijunglist** [comment]
Hi. I'm not using HA or the camera currently so I can't confirm or deny this from another user perspective.
