### ISSUE TITLE
Is VTO2202F-P-S2 supported?

### ISSUE THREAD

**Issue by felipecrs** [rroller/dahua#107]
First of all, awesome project!

This seems to be an updated revision of VTO2202F-P, with support for Dahua's 2-wire switch. But apart from that, there are improvements on the camera angles and also this model supports H.265 if compared with the VTO2202F-P.

Currently, it's much easier to find it to buy in AliExpress than to find VTO2202F-P, so before buying, I'm questioning here... to potentially avoid making a wrong assumption.

- VTO2202F-P-S2: https://www.dahuasecurity.com/products/productDetail/60597
- VTO2202F-P: https://www.dahuasecurity.com/br/products/All-Products/Video-Intercoms/2-Wire-Series/Villa-Door-Station/Pro-Series/VTO2202F-P

Any thoughts?

**Comment by jbagot** [comment]
Hey, yes is supported. I have this product (I also boght it from Aliexpress) and I already have integrated with my home assistant.
I can see the video in stream and also I created an automation when someone ring the bell a sound is played in my Sonos speaker.
Now I'm checking how to do the call inside the home assistant and so on... I'm not there yet.

**Comment by Lepelot** [comment]
Hello, I have the same Dahua camera, but I get ("User input malformed") when trying to install the integration.  if I don't select "events", I get this other message: Error: Username, Password, or Address is wrong.
Not sure what to do next.
I don't know if it's related, but I am also unable to get ring button notifications on my phone either. The video and audio streams are fine on the phone and on the recorder (Blue Iris). 
I'd appreciate any comment you guys might have. Thanks.

**Comment by Lepelot** [comment]
Slight progress today: I can now start the integration if I don't select any event in the configuration.

**Comment by rroller** [comment]
I only have the VTO2202F-P which works fine. I can't repro any issues. Let's track the malformed issue here - https://github.com/rroller/dahua/issues/110

Otherwise, looks like it works if you don't select events
