### ISSUE TITLE
Impossible to add my cam : Imou Ranger 2C (NOMI-IPC-TA22C)

### ISSUE THREAD

**Issue by Dim3333** [rroller/dahua#108]
Hello,

I can't add my cam (Imou Ranger 2C) with HA integration. Each time, I have the message "Username, Password, or Address is wrong."
It's works with ONVIF integration.

![image](https://user-images.githubusercontent.com/43283756/139337976-fdf9433a-c43c-451c-9933-058f2b642047.png)

The password is the safety code written under the camera.

Thanks for your help.

**Comment by goblinmaks** [comment]
#6

**Comment by rroller** [comment]
These are not well supported yet. Please follow https://github.com/rroller/dahua/issues/6
