### ISSUE TITLE
I can't add Imou IPC-F22A

### ISSUE THREAD

**Issue by danimart1991** [rroller/dahua#112]
## Version of the custom_component
0.9.24

## Describe the bug
Hello,

I can't add my cam (Imou IPC-F22A) with HA integration. Each time, I have the message "Username, Password, or Address is wrong."

- It works with ONVIF integration.
- RTSP Url is: rtsp://admin:pass@192.168.1.209:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif (works with subtype 1 too).
- It works on Dahua Smart PSS.

## Debug log

![image](https://user-images.githubusercontent.com/5982912/142723198-ddce889d-898c-491e-aea7-814391ef8e39.png)

**Comment by rroller** [comment]
These are not well supported yet. Please follow https://github.com/rroller/dahua/issues/6
