### ISSUE TITLE
ASH26 Amcrest Security/Flood Light

### ISSUE THREAD

**Issue by itkfilelor** [rroller/dahua#113]
``**Is your feature request related to a problem? Please describe.**
'Illuminator' is not discovered on set up.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Add a "advanced" mode to allow users to select their own lights as a catch-all for such circumstances.

**Additional context**
I already have this set up using shell commands, but for whatever reason they are not very reliable on my machine via HA. 
For this particular camera/light the API does not return the white light correctly. See below.
For my unit:
`Lighting_V2[0][0][1]`
is the flood light controller
where as the api returns 
`Lighting_V2[0][2][1]`
which does nothing (that i can see anyway)

Also the integration does not even pick anything up that is a light apart from the IR

Command:
`http://floodlight.lan/cgi-bin/configManager.cgi?action=getConfig&name=Lighting_V2`
Response:
table.Lighting_V2[0][0][0].Correction=50
table.Lighting_V2[0][0][0].LightSwitchDelay=0
table.Lighting_V2[0][0][0].LightType=InfraredLight
table.Lighting_V2[0][0][0].MiddleLight[0].Angle=50
table.Lighting_V2[0][0][0].MiddleLight[0].Light=50
table.Lighting_V2[0][0][0].Mode=Auto
table.Lighting_V2[0][0][0].Sensitive=3
table.Lighting_V2[0][0][1].Correction=50
table.Lighting_V2[0][0][1].LightSwitchDelay=0
table.Lighting_V2[0][0][1].LightType=WhiteLight
table.Lighting_V2[0][0][1].Mode=Off
table.Lighting_V2[0][0][1].NearLight[0].Angle=50
table.Lighting_V2[0][0][1].NearLight[0].Light=50
table.Lighting_V2[0][0][1].Sensitive=3
table.Lighting_V2[0][1][0].Correction=50
table.Lighting_V2[0][1][0].LightSwitchDelay=0
table.Lighting_V2[0][1][0].LightType=InfraredLight
table.Lighting_V2[0][1][0].MiddleLight[0].Angle=50
table.Lighting_V2[0][1][0].MiddleLight[0].Light=50
table.Lighting_V2[0][1][0].Mode=Auto
table.Lighting_V2[0][1][0].Sensitive=3
table.Lighting_V2[0][1][1].Correction=50
table.Lighting_V2[0][1][1].LightSwitchDelay=0
table.Lighting_V2[0][1][1].LightType=WhiteLight
table.Lighting_V2[0][1][1].Mode=Off
table.Lighting_V2[0][1][1].NearLight[0].Angle=50
table.Lighting_V2[0][1][1].NearLight[0].Light=50
table.Lighting_V2[0][1][1].Sensitive=3
table.Lighting_V2[0][2][0].Correction=50
table.Lighting_V2[0][2][0].LightSwitchDelay=0
table.Lighting_V2[0][2][0].LightType=InfraredLight
table.Lighting_V2[0][2][0].MiddleLight[0].Angle=50
table.Lighting_V2[0][2][0].MiddleLight[0].Light=50
table.Lighting_V2[0][2][0].Mode=Auto
table.Lighting_V2[0][2][0].Sensitive=3
table.Lighting_V2[0][2][1].Correction=50
table.Lighting_V2[0][2][1].LightSwitchDelay=0
table.Lighting_V2[0][2][1].LightType=WhiteLight
table.Lighting_V2[0][2][1].Mode=Off
table.Lighting_V2[0][2][1].NearLight[0].Angle=50
table.Lighting_V2[0][2][1].NearLight[0].Light=50
table.Lighting_V2[0][2][1].Sensitive=3

**Comment by itkfilelor** [comment]
I found what appears to be the code block that is stopping the light from being discovered
[custom_components/dahua/__init__.py Line 482](https://github.com/rroller/dahua/blob/83c09300098b6e446d218a60280a7d5babfd2c6f/custom_components/dahua/__init__.py#L482)
`
    def supports_illuminator(self) -> bool:
        """
        Returns true if this camera has an illuminator (white light for color cameras).  For example, the
        IPC-HDW3849HP-AS-PV does
        """
        return "table.Lighting_V2[{0}][0][0].Mode".format(self._channel) in self.data
`
This could also assist with [this question](https://github.com/rroller/dahua/issues/52#issuecomment-949769445) from #52 
I can try and stab at it myself, but I've never made an integration before and a lot of this code is bigger than anything I've ever made.
I'll see if I can through together a method similar to the doorbell check using the ASH model until something better can be put together by someone smarter.

**Comment by rroller** [comment]
I've started to work on this. This is what it'll look like. The options will be: Off, On, Strobe. 

This seem OK? I should have this done tomorrow.

<img width="343" alt="Screen Shot 2021-12-24 at 11 09 04 PM" src="https://user-images.githubusercontent.com/445655/147379602-79775613-c24a-4ba2-ab66-c569b5b57678.png">

**Comment by rroller** [comment]
The security light feature is released in https://github.com/rroller/dahua/releases/tag/0.9.28

**Comment by rroller** [comment]
Resolving this issue now that the security light (illuminator) is now supported with this integration. Please reopen if you have any issues.

**Comment by itkfilelor** [comment]
WOW! great work! thank you!

**Comment by mpjanofsky** [comment]
Just set up my Amcrest floodlight using this integration and I’m not getting the Illuminator toggle. Is there any additional setup needed?

**Comment by itkfilelor** [comment]
The main main integration currently does not support Amcrest Floodlights, try using PR [141](https://github.com/rroller/dahua/pull/167)
