### ISSUE TITLE
No audio in video stream

### ISSUE THREAD

**Issue by mafelipe16** [rroller/dahua#114]
## Version of the custom_component
0.9.24
## Configuration

  - platform: dahua_vto
    name: Puerta Principal
    host: 192.168.1.47
    username: admin
    password: xxxxxx
    scan_interval: 5

No logs

## Describe the bug
When selecting the Main or Sub stream there is no audio

**Comment by rroller** [comment]
I don't  recommend using HA as a way to view the streams. It's great to control the camera but not for a stream viewing app.
