### ISSUE TITLE
Amcrest AD410 stops working after a day

### ISSUE THREAD

**Issue by stingone** [rroller/dahua#115]
I installed an integrated the AD410. however the intergration stops working after a day. when reloading the plugin works again

checking the log i get erros below.. 

`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.dahua
Source: custom_components/dahua/vto.py:105
Integration: Dahua (documentation, issues)
First occurred: 27 november 2021 17:28:10 (731 occurrences)
Last logged: 21:36:43

Failed to handle message, error: 'NoneType' object has no attribute 'get', Line: 97`

`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.dahua
Source: custom_components/dahua/vto.py:393
Integration: Dahua (documentation, issues)
First occurred: 27 november 2021 17:28:10 (346 occurrences)
Last logged: 21:36:43

Failed to read data: b' \x00\x00\x00DHIP^\xc1\xb6K\x08\x00\x00\x00#\x01\x00\x00\x00\x00\x00\x00#\x01\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","', error: substring not found, Line: 385
Failed to read data: b' \x00\x00\x00DHIP^\xc1\xb6K\x08\x00\x00\x00\x1d\x01\x00\x00\x00\x00\x00\x00\x1d\x01\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","', error: substring not found, Line: 385
Failed to read data: b' \x00\x00\x00DHIP^\xc1\xb6K\x08\x00\x00\x009\x01\x00\x00\x00\x00\x00\x009\x01\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","', error: substring not found, Line: 385
Failed to read data: b' \x00\x00\x00DHIP^\xc1\xb6K\x08\x00\x00\x00#\x01\x00\x00\x00\x00\x00\x00#\x01\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"TimeChange","Data":{"BeforeModifyTime":"2021-12-01 21:36:43","LocaleTime":"2021-12-01 21:36:43","ModifiedTime":"2021-12-0', error: substring not found, Line: 385
Failed to read data: b' \x00\x00\x00DHIP^\xc1\xb6K\x08\x00\x00\x00\x1d\x01\x00\x00\x00\x00\x00\x00\x1d\x01\x00\x00\x00\x00\x00\x00{"id":8,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"NTPAdjustTime","Data":{"Address":"200.160.0.8","Before":"2021-12-01 21:36:37","LocaleTime":"2021-12-01 21:36:43","UTC":16', error: substring not found, Line: 385`

`Logger: amcrest.http
Source: /usr/local/lib/python3.9/site-packages/amcrest/http.py:299
First occurred: 27 november 2021 15:49:45 (164 occurrences)
Last logged: 20:47:51

<Unconnected @ 192.168.1.39> Trying again due to error: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.1.39', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at ADDRESS>, 'Connection to 192.168.1.39 timed out. (connect timeout=6.05)'))"))
<Unconnected @ 192.168.1.39> Trying again due to error: ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='192.168.1.39', port=80): Read timed out. (read timeout=6.05)"))`

**Comment by HeedfulCrayon** [comment]
Did you reserve the IP address of your doorbell?  If your doorbell got a new ip address, it would most likely cause this issue

**Comment by stingone** [comment]
I have indeed given it mac/ip adress binding.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by stingone** [comment]
I have removed ip/mac binding in router and set a static ip via the amcrest app. Seems stable now...

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by rroller** [comment]
I bought one of these just so I could test it out and fix some features for the doorbell (like making it so we can turn the light on/off). I've had it plugged in for some time and haven't had any issues. Sounds like you got yours resolved too so going to resolve this issue. Thanks!
