### ISSUE TITLE
several logins/logouts per second on my Dahua cam

### ISSUE THREAD

**Issue by jaegerschnitzel** [rroller/dahua#118]
Under my Dahua camera log, I can see that Home Assistant creates several logins and logouts per second.
Just wanted to know if that's normal behavior and if yes  why this is happening.

1 | 2021-12-06 20:39:23 | homeassistant | Logout
2 | 2021-12-06 20:39:23 | homeassistant | Logout
3 | 2021-12-06 20:39:23 | homeassistant | Logout
4 | 2021-12-06 20:39:22 | homeassistant | Logout
5 | 2021-12-06 20:39:22 | homeassistant | Login
6 | 2021-12-06 20:39:22 | homeassistant | Login
7 | 2021-12-06 20:39:22 | homeassistant | Login
8 | 2021-12-06 20:39:22 | homeassistant | Login
9 | 2021-12-06 20:39:22 | homeassistant | Logout
10 | 2021-12-06 20:39:22 | homeassistant | Login

**Comment by Scoobs72** [comment]
I'm seeing the same behavior.  Seems unusual.

**Comment by rroller** [comment]
I think I have an idea why. I was attempting to use the RPC API which requires logging in/out (or to do some session management). I believe that's why. I think I'm going to remove support for the RPC API and just use the HTTP API which doesn't require logging in/out.

**Comment by rroller** [comment]
I removed it in this commit - https://github.com/rroller/dahua/commit/cd694e09934e8b102eda0a2103640c39886ec7f7

I'll publish a new release later today. Please reopen if you continue to see this.

But looking at it more, I'm not sure where that log is coming from. This integration doesn't emit that log anywhere in the code.

**Comment by jaegerschnitzel** [comment]
Thanks for your response. Unfortunately I still have these log entries. Perhaps a bit less frequent but still a lot.

That log is directly from the camera:
![grafik](https://user-images.githubusercontent.com/4368865/147876211-0d2aa936-4fe5-465b-b563-2622005f30d3.png)

**Comment by rroller** [comment]
That's likely because the integration needs to refresh every 30 seconds or so ti see what changed. When it does it fires off a few calls in parallel to the camera and those will show as a login as each request needs to login. I'll see if I can cache the login to reduce the log entries.

**Comment by jaegerschnitzel** [comment]
> I'll see if I can cache the login to reduce the log entries.

That would be great. Thanks for your effort!

**Comment by jaegerschnitzel** [comment]
Did you manage to look in the caching mechanism in the meantime?

**Comment by hirppa10** [comment]
Any update on this? This login/logout process makes dahua's log pretty useless as it's flooded with login/logout rows. I will get one for every 10 seconds.
