### ISSUE TITLE
AD410 not reporting button doorbell button presses

### ISSUE THREAD

**Issue by DeltaNu1142** [rroller/dahua#119]
I've been monitoring `binary_sensor.front_doorbell_button_pressed` and `binary_sensor.front_doorbell_call_no_answered`, and unfortunately neither of them report the doorbell button press consistently. `button_pressed` doesn't change state at all, which I expected; `call_no_answered` changes state, but remains in a state of `detected` for up to an hour following a button press.

I've also noticed that I have no listing for dahua or amcrest under Active Listeners, here: `https://<HA-IP>/developer-tools/event`.

**Comment by rroller** [comment]
I bought an AD410 so I can work on getting this in very good shape. I'll have some free time soon and plan on working out all the issues (to the best that they can be)

Also btw, if you use the events, things work a lot better. The sensor is just a nice-to-have.  I have some examples in the readme.

**Comment by DeltaNu1142** [comment]
Ah, OK. I've just set up my automation to look for a `dahua_event_received` event. I'm using Node-RED. Unfortunately, I've introduced a little delay that I wasn't seeing with the sensor state change... I don't know why. I'd expect it to be faster.

![Node-RED](https://user-images.githubusercontent.com/77296070/145726680-e4ed76f4-91b2-49c8-b426-3ed42c0ccd4b.png)

Anyway, yes, that works! Thanks.

**Comment by ruant** [comment]
I'm having issues with this as well.
Getting some errors in the logs, but not sure if it's related or it's something else I've broken.

`[custom_components.dahua] Connection to VTO failed will try to connect in 30 seconds, error: [Errno -2] Name does not resolve, Line: 110`

**Comment by rroller** [comment]
I've just released https://github.com/rroller/dahua/releases/tag/0.9.27 which should fix this. The sensor is now keyed off of the `PhoneCallDetect` event.

**Comment by rroller** [comment]
Please reopen if you have issues with the latest version. I tested it locally and it seems to work fine.
