### ISSUE TITLE
Adding more than 2 cameras causes an existing camera to lose entities

### ISSUE THREAD

**Issue by DDDaveBell** [rroller/dahua#12]
Added 2 cameras to the Dahua integration without problem.
When the third was added all entities of one of the existing cameras were lost.
That camera still appears as a device, but with no entities.
The newly added camera is OK.

**Comment by DDDaveBell** [comment]
Additional information: If adding any cameras after the first two, then restarting HA seems to be required. After a restart all devices and all entities are present.

**Comment by rroller** [comment]
I've not been able to reproduce this. Is this related to renaming the cameras?

**Comment by rroller** [comment]
I fixed the renaming bug in 0.7.1

Please give that a try and let me know if you still have issues.

**Comment by rroller** [comment]
I will resolve this. I cant reproduce the issue and it's possible that the issue you had were from other bugs.

Please feel free to reopen this if you have any issues. Thank you!

**Comment by DDDaveBell** [comment]
Just tried again and looks OK now, so was probably related to other issues as you suggest.
