### ISSUE TITLE
Intercom Features for AD410

### ISSUE THREAD

**Issue by ronscharf1** [rroller/dahua#122]
Hi-

I just got an AD410, and the integration seems to be working well for recognizing the button press and streaming the video.
But is there any way to enable the audio communication features?

I am trying to set this up on a kindle fire dashboard, and it seems like if I want to be able to actually speak to the person at the door, I have to use Home Habit because it lets me both see the stream on the dashboard, and also have a separate button that launches the Amcrest app.  

It would be great to somehow be able to enable that function directly on the stream or through a lovelace button so I don't have to leave the dashboard and come back. 

Any thoughts on that?

Thanks so much!

**Comment by rroller** [comment]
Thanks for the request. I'll track this issue in https://github.com/rroller/dahua/issues/55 so please follow that one. Warning, this probably won't be easy so not sure when or if I can do it.
