### ISSUE TITLE
Support for "abandoned object" IVS type

### ISSUE THREAD

**Issue by test32443** [rroller/dahua#123]
**Is your feature request related to a problem? Please describe.**
I am using Dahua HDW5442T-ZE camera. I do see support for "Tripwire" and "Intrusion" type of IVS rules, and I do see them coming as events, but I do not see support for "Abandoned object" rule and it does not come as event from camera. "Abandoned Object" detection seems to work better on 5442T, especially during nighttime.

**Describe the solution you'd like**
I would like to see support added to support "Abandoned object" IVS rule

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here
![ivs](https://user-images.githubusercontent.com/29136362/146864801-62487c70-2cd6-4d99-a484-9eba3c0a57bc.png)
.

**Comment by rroller** [comment]
> I do see them coming as events

Can you enable debug logging and paste the event json to me?

**Comment by rroller** [comment]
In Dahua I believe this is called "LeftDetection"

**Comment by rroller** [comment]
This should be supported already. You just need to select the event type as `LeftDetection` when you configure the camera. For some reason Dahua gives it two names and the actual name is `LeftDetection`

**Comment by rroller** [comment]
I'll resolve this since it is already supported (just with a different name). Please reopen if you have issues.
