### ISSUE TITLE
IMOU IPC-A22E-A (bricked firmware)

### ISSUE THREAD

**Issue by goku600** [rroller/dahua#125]
HI Devs , i have an "IMOU RANGER-2" IP camera which got bricked during a 
firmware upgrade followed by a powercut. it does not respond after that. Only a continuous red light is on the ip camera. what can i do to fix it back. I searched online for its official firmware but it was'nt available .

your help would be appreciated......

**Comment by rroller** [comment]
Sorry this wouldn't be the right place to ask such questions. 

You might ask on https://ipcamtalk.com/forums/dahua.8/
