### ISSUE TITLE
Event Binary Sensor

### ISSUE THREAD

**Issue by HappySl0th** [rroller/dahua#13]
I have a IPC-T5442T-ZE setup with 2 IVS rules, the first is a general motion detector and the second one is a tripwire which I am hoping to use this for automation. Under my integration, my device only shows 5 entities (Cam Disarming, Cam Infrared, Cam Main, Cam Motion Alarm and Cam Motion Detection) and I do not have separate event binary for CrossLineDetection or FaceDetection, even though I have this enabled on the camera and integration. I am using the latest version installed via HACS.

**Comment by rroller** [comment]
Got it. I'll work on this now and try to get it added ASAP.

**Comment by rroller** [comment]
The is merged in https://github.com/rroller/dahua/pull/16

NOTE: This needs the camera's IVS SmartPlan to be enabled, which I'm sure you already have enabled.

The is released in 0.5.3 https://github.com/rroller/dahua/releases/tag/0.5.3

<img width="338" alt="Screen Shot 2021-06-18 at 2 02 10 PM" src="https://user-images.githubusercontent.com/445655/122615694-c7e22080-d03d-11eb-9c55-5589e75140ad.png">
