### ISSUE TITLE
Link https://github.com/rroller/dahua/archive/dahua-main.zip doesn't work?

### ISSUE THREAD

**Issue by JimGermany** [rroller/dahua#130]
I wanted to test the current version first but the Link doesn't work?

Dahua integration: 0.9.26 
HA: core-2021.12.7
Dahua SD49225T-HN, Dahua SD1A203T-GN-W, Amcrest AD110

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 16:54:05 (43 occurrences)
Last logged: 16:54:06

    Entity camera.ad110_door_main (<class 'custom_components.dahua.camera.DahuaCamera'>) implements device_state_attributes. Please report it to the custom component author.
    Entity switch.dahuahof_motion_detection (<class 'custom_components.dahua.switch.DahuaMotionDetectionBinarySwitch'>) implements device_state_attributes. Please report it to the custom component author.
    Entity switch.dahuaeinfahrt_motion_detection (<class 'custom_components.dahua.switch.DahuaMotionDetectionBinarySwitch'>) implements device_state_attributes. Please report it to the custom component author.
    Entity switch.ad110_door_motion_detection (<class 'custom_components.dahua.switch.DahuaMotionDetectionBinarySwitch'>) implements device_state_attributes. Please report it to the custom component author.
    Entity switch.dahuaschuppen_motion_detection (<class 'custom_components.dahua.switch.DahuaMotionDetectionBinarySwitch'>) implements device_state_attributes. Please report it to the custom component author.
`

**Comment by rroller** [comment]
This was fixed in https://github.com/rroller/dahua/commit/1287a0891bf4e12e31c9648e0c1f289446613c76

Seems you are pulling an old version?

Try this version https://github.com/rroller/dahua/releases/tag/0.9.30

**Comment by thisisdavidbell** [comment]
FYI, the link in the main README still points to this value for the manual install, so following those instructions does not work.
