### ISSUE TITLE
Support Dahua doorbells

### ISSUE THREAD

**Issue by bogdanr** [rroller/dahua#14]
I am using this integration with my doorbell and it seems to work but it's missing the doorbell button binary_sensor. It would be very cool to have that too.

**Comment by rroller** [comment]
I also have a Dahua doorbell. I'm not sure what you mean by the doorbell button binary_sensor. I'll dig into it and try to find out and add support for it. Luckily I have a unit already so I can test easily. I'll keep you posted.

Is this just a sensor that triggers when the doorbell is pressed?

**Comment by rroller** [comment]
@bogdanr This is done and added in [0.7.0](https://github.com/rroller/dahua/releases/tag/0.7.0)

It'll add a binary sensor for the button press:

<img width="365" alt="Screen Shot 2021-06-19 at 3 53 52 PM" src="https://user-images.githubusercontent.com/445655/122657234-8ffadc00-d116-11eb-99b8-8a610ec46669.png">

**Comment by rroller** [comment]
Please reopen if there's any issues. Thanks!

**Comment by danuals** [comment]
could this support amcrest doorbells too?

**Comment by rroller** [comment]
I don't know. Would just have to try.

**Comment by danuals** [comment]
just have, video feed ok, 
motion alert works,
 inferred switch does off- auto.   
motion detection doesn't seem to switch on/off at device. 
no binary sensor for button press.   callnotanswered and invite are the same messages afaik

**Comment by danuals** [comment]
great integration btw, my Dahua cam works a treat with it, thank you

**Comment by HappySl0th** [comment]
@rroller I have a VTO2202F doorbell which have remote unlocking, can you add this as a binary sensor?

**Comment by rroller** [comment]
@HappySl0th sure! Can you enable debug logging and send me the event data in the logs? The event is already fired on the HA event bus so you might be able to capture it there. Once I know the event details I can add the sensor.

**Comment by rroller** [comment]
Also can you create a new issue to track this in.
