### ISSUE TITLE
Config option for sensor not visible

### ISSUE THREAD

**Issue by jgverweij** [rroller/dahua#144]
In config options an empty line is present:
![Screenshot_20220117-212617](https://user-images.githubusercontent.com/78507418/149833589-1ff4ef81-e5e8-4432-8d38-d487896c0dc4.png)

This seems to result from sensor not being present in PLATFORMS in const.py

## Version of the custom_component
0.9.3.2

**Comment by rroller** [comment]
What version of home assistant are you on?

**Comment by rroller** [comment]
Ohh, I can reproduce this. I'll work on a fix.

**Comment by rroller** [comment]
Fixed in https://github.com/rroller/dahua/releases/tag/0.9.34
