### ISSUE TITLE
Amcrest AD410: Indicator Light Switch

### ISSUE THREAD

**Issue by JamesUK4576** [rroller/dahua#150]
Would it be possible to expose the "Indicator Light Switch" in this integration for the Amcrest AD410 doorbell, it toggles the blue light around the doorbell button and is an option available in the amcrest app.

Thanks for all your hard work so far.

Best Regards,
James

**Comment by rroller** [comment]
Looks like this is how to control that...

```
/cgi-bin/configManager.cgi?action=setConfig&LightGlobal[0].Enable=true
/cgi-bin/configManager.cgi?action=setConfig&LightGlobal[0].Enable=false
/cgi-bin/configManager.cgi?action=getConfig&name=LightGlobal[0].Enable
```

I'll work on this ASAP.

**Comment by rroller** [comment]
This is now supported in version 0.9.38

https://github.com/rroller/dahua/releases/tag/0.9.38

**Comment by rroller** [comment]
Will resolve this now that it is supported
