### ISSUE TITLE
VTO4202F supported?

### ISSUE THREAD

**Issue by roccotocco** [rroller/dahua#152]
Hello, i would like to configure my dahua doorbell VTO4202F but the integration do not working..... VTO4202F is compatible ? there's a way to configure it ?
Thanks

**Comment by mooton85** [comment]
You can try the following picture entity card I just tried for the VTO2202F-P. Their firmware is very similar so I would suspect it will work. Just make sure to rename the vto entities to whatever you named yours......

type: picture-entity
entity: camera.door_main
tap_action:
  action: call-service
  service: dahua.vto_open_door
  service_data: {}
  target:
    entity_id: camera.door_main

**Comment by rroller** [comment]
Sorry, I don't have this model so I can't test it. There's not a lot I can do otherwise.
