### ISSUE TITLE
Compatibility with DHI-NVR5208-8P-4KS2 eight channel NVR ?

### ISSUE THREAD

**Issue by tomlut** [rroller/dahua#155]
Is this integration compatible with the DHI-NVR5208-8P-4KS2 eight channel NVR?

Can I get smart motion events and camera streams and snapshots from it?

The NVR's 8 port PoE switch uses the same network range as my home network (10.1.1.0/24). So if I use the NVR PoE switch I will have to change that network range potentially making my cameras unreachable directly via HA and only via the NVR.

I have enough PoE ports on my 48 port switch though, so could use these instead. I'd like to use the NVR switch to minimise unneeded traffic in my main 48 port switch but can go with the 48 port switch if I have to connect directly to the cameras using this integration. 

The cameras I'm using are  DH-IPC-HDW3841EMP-AS-0280B.

**Comment by thetravellor** [comment]
bump

**Comment by mooton85** [comment]
I have an NVR5416-16P-4KS2 working no problem streaming video and receiving events (including motion). This uses the same version of firmware as your unit, firmware version is V4.001.0000007.1 Build Date 27-08-2021

**Comment by tomlut** [comment]
Brilliant! That's exactly what I wanted to know. Thanks for the information.
