### ISSUE TITLE
CrossRegionDetection = Intrusion 

### ISSUE THREAD

**Issue by f432** [rroller/dahua#17]
Would be good to add the additional IVS feature: CrossRegionDetection = Intrusion

This allows more functionality for IVS in addition to the tripwire feture

**Comment by rroller** [comment]
Thanks. I'll try to look into this today

**Comment by rroller** [comment]
Looking at this now and it'll be straight forward. My plan is to generalize the sensors for events so we just get a sensor for every event selected during the integration setup.

**Comment by rroller** [comment]
This is done and released in [0.6.0](https://github.com/rroller/dahua/releases/tag/0.6.0) which should update in HACS soon.

**Comment by rroller** [comment]
Note: The code is generalized now so there will be a sensor for each event type selected during the config flow setup.

https://github.com/rroller/dahua/pull/18
