### ISSUE TITLE
No event messages

### ISSUE THREAD

**Issue by Ryukenden88** [rroller/dahua#206]
Im no longer receiving event messages from the ad410 doorbell. The streaming still works.

**Comment by rroller** [comment]
Can you please try the latest version 0.9.43?

I added a better JSON extractor that will handle extracting multiple JSON elements from a string and handle multi line elements

https://github.com/rroller/dahua/releases/tag/0.9.43

**Comment by rroller** [comment]
Will close this. Please let me know if this works though. 

Here's the issue tracking this problem - https://github.com/rroller/dahua/issues/148

**Comment by Ryukenden88** [comment]
The update seems to have fixed it. Thank you:)
