### ISSUE TITLE
Using the integration to recover the password

### ISSUE THREAD

**Issue by Sagi-tab** [rroller/dahua#238]
I'm using Amcrest AD410 that requires a device password that cannot be recovered. I've set up this integration before I forgot the device's password.
Since the integration is storing this password somewhere - is there a way to recover it from storage somehow? It would help me a lot (and other users, I'm sure).

Thanks!

**Comment by GaryOkie** [comment]
Of course a factory reset will let you redefine a new password.

Or -  take a took at **_/config/.storage/core.config_entries_**  under the "dahua" domain.

**Comment by Sagi-tab** [comment]
I was trying to avoid a factory reset. And your suggestion worked wonderfully! Thank you @GaryOkie !
