### ISSUE TITLE
Supported Device: Intelbras VIP3230D (white label from Dahua IPC-HDBW1230E-S2 in Brazil)

### ISSUE THREAD

**Issue by dougiteixeira** [rroller/dahua#25]
Hi, this is great!
I performed the test with the Intelbras VIP 3230 D camera (white label from Dahua IPC-HDBW1230E-S2 in Brazil) and it has worked well, with the exception of the video stream which works intermittently and does not show an error log when it is in the unavailable status.

**Comment by rroller** [comment]
Awesome, thank you! I'll update the readme with this info.

Home Assistant doesn't really work well for watching video streams. The best way I've found is this...
https://github.com/AlexxIT/WebRTC
