### ISSUE TITLE
Cross Region Detection - IVS Intrusion not working

### ISSUE THREAD

**Issue by f432** [rroller/dahua#26]
Not getting any responses to Cross Region Detection. I've reinstalled and cross line alarm works but not cross region.

I've added the log entry into configurations.yaml but when checking the side bar logs I don't see any entries, assume I'm looking in the wrong place for the logs.

**Comment by rroller** [comment]
When you added the integration, did you select `CrossRegionDetection` in the event list?

**Comment by f432** [comment]
yes, that and Cross Line alarm which works fine. 

![image](https://user-images.githubusercontent.com/67050404/122816210-b9fafc80-d2d6-11eb-9afe-aa709d3a6f7a.png)

Not working across 3 cameras and def. configured in the camera settings for all 3

**Comment by rroller** [comment]
Got it, thanks. I'm going to set this up on one of my cameras and debug the issue -- those screenshots help a lot. I'll do that later today and report back.

**Comment by rroller** [comment]
I can't get `CrossRegionDetection` to fire at all in the camera. I can only make it fire `VideoMotion` and `SmartMotionHuman` events. The event data contains more details like the region, etc. Those events are fired on the Home Assistant event bus and you can use that for automations if you like.  The question I have is, how do we make `CrossRegionDetection` events fire with Dahua cameras? I tried combinations of IVS, motion enabled, smart motion, etc. 

```
Code=VideoMotionInfo;action=State;index=0

Code=VideoMotion;action=Start;index=0;data={
   "Id" : [ 0 ],
   "RegionName" : [ "Region1" ],
   "SmartMotionEnable" : true
}

Code=SmartMotionHuman;action=Start;index=0;data={
   "RegionName" : [ "Region1" ],
   "WindowId" : [ 0 ],
   "object" : [
      {
         "HumamID" : 8,
         "Rect" : [ 3632, 3184, 4816, 8144 ]
      }
   ]
}


Code=SmartMotionHuman;action=Stop;index=0;data={
   "RegionName" : [ "Region1" ],
   "WindowId" : [ 0 ],
   "object" : [
      {
         "HumamID" : 8,
         "Rect" : [ 3824, 3696, 4728, 8096 ]
      }
   ]
}

Code=VideoMotion;action=Stop;index=0;data={
   "Id" : [ 0 ],
   "RegionName" : [ "Region1" ],
   "SmartMotionEnable" : true
}
```

**Comment by f432** [comment]
I checked my IVS cross region detection was working correctly from the camera's perspective when using IE and the "live" section was flashing when it was hit. 

I used this attached code in a container that was able to send an HTTP request for CRD, not sure if it helps. HA is so much easier to work with as getting this code to scale to 5 cameras was beyond me 

[dahua-ivskitchen.zip](https://github.com/rroller/dahua/files/6700017/dahua-ivskitchen.zip)

If CRD doesn't work it's not an issue as IVS via Cross line Detection is just as good.

**Comment by rroller** [comment]
OK awesome. I wasn't able to make any progress on this because I couldn't find any way to trigger CRD with my cameras. 

I'll keep an eye open and reopen this if I find a way. Sorry I don't have a better answer but glad you have a solution.
