### ISSUE TITLE
Readme needs change for the Stream component

### ISSUE THREAD

**Issue by TheDukeSr** [rroller/dahua#27]
Just a small update:

In the readme you state stream is needed in the config.yaml
But according to this url (I checked and can confirm this): [Hass Stream Component](https://www.home-assistant.io/integrations/stream/ 
)
> The stream integration is automatically loaded by default_config and enabled by the camera platforms that support it. If default_config is used, no separate configuration.yaml entry is necessary.

ps. Readme FFMpeg part is correct. FFmpeg is NOT included (yet?), and needs to be added to the config.yaml

Regards, The Duke.

**Comment by rroller** [comment]
Thank you! Updated https://github.com/rroller/dahua/blob/main/README.md
