### ISSUE TITLE
IVS Detections not being picked up on dahua_event_recieved

### ISSUE THREAD

**Issue by Lloyd-Davies** [rroller/dahua#277]
The IVS events (tripwire and intrusion) are visible in the alarm section of the Dahua Web ui, but are not being shown in home assistant. Something must be wrong with the way the API is being queried for these events, hopefully a simple fix!

I have attempted to listen for the events through the developer options but nothing is coming through despite the cameras triggering these alerts in the Dahua ui. Below is a screenshot showing one of these alerts, they appear under the "Intelligent" section.

![image](https://github.com/rroller/dahua/assets/39085284/9f4ca820-287e-4846-b80f-a020497229fa)

I have not been able to find any errors relating to this in the HA Core logs, though I'm not sure if my logs are reporting at debug level or not, if you could please advise on this that would be great.

My device is: XVR5108C-X

The Smart Motion Human Events were working fine, however, I was getting lots of false positives using this in the dark so I want to use IVS instead, hopefully this can be sorted!

**Comment by Lloyd-Davies** [comment]
RESOLVED: Added integration device again with different XVR login credentials and the motion alerts are all working correctly now.

**Comment by lionslair** [comment]
> 

what do you mean different login?
