### ISSUE TITLE
Light Illuminator not working when profile is set as "night"

### ISSUE THREAD

**Issue by f432** [rroller/dahua#29]
Switching on the LED light via HA works fine when the profile is the day but not when the profile is at night.

Log here: 2021-06-23 15:23:50 DEBUG (MainThread) [custom_components.dahua] Turning light on: http://192.168.10.20:80/cgi-bin/configManager.cgi?action=setConfig&Lighting_V2[0][0][0].Mode=Manual&Lighting_V2[0][0][0].MiddleLight[0].Light=20

It does work with the following URL: 

http://192.168.10.20/cgi-bin/configManager.cgi?action=setConfig&Lighting[0][2].Mode=Manual

So night profile needs to be stated in the URL as [2] Any idea if this can be amended as it's great to control the brightness via HA.

thanks

**Comment by rroller** [comment]
Got it, thanks. This is easy to reproduce. I'll report back once I have a solution.

**Comment by rroller** [comment]
This is fixed in 0.8.2

Please let me know if that works for you. I also need to apply this same fix for other areas of the code, like the infrared light.

Thank you for reporting the issue!

**Comment by f432** [comment]
Works perfectly, many thanks
