### ISSUE TITLE
DH-SD1A203T-GN audio event

### ISSUE THREAD

**Issue by gzone156** [rroller/dahua#32]
The DH-SD1A203T-GN camera has an onboard mic and can generate "audio detection" event.

It would be nice to have a binary sensor representing this event. As an additional note, the event already get fired in Onvif stream.

If you need any further info, I'll be glad to help. Thanks.

**Comment by rroller** [comment]
When you setup the camera in Home Assistant, did you select `AudioAnomaly` in the event list? I'm wondering if that is the event you are looking for? And FYI, all events are fired on the HA event bus regardless if you selected them or if they have a sensor. So at the very least, you can just capture the event on the event stream... but, I'd definitely like to make sure I can support a sensor for this. Please let me know if `AudioAnomaly` is what you are looking for... you'll need to remove the camera and add it back and select `AudioAnomaly`.

<img width="386" alt="Screen Shot 2021-06-27 at 3 55 54 PM" src="https://user-images.githubusercontent.com/445655/123561924-299e3b00-d760-11eb-9969-4abebde7bc23.png">

**Comment by rroller** [comment]
Also just an FYI, all events by the camera are fired on the HA event bus. I've updated the readme on how you'd create automations around that - https://github.com/rroller/dahua/blob/main/README.md#events

I still want to make sure I get a sensor directly for this though. I plan on testing with my cams as soon as I get a little more time.

**Comment by rroller** [comment]
OK, I found out the real event name, it's `AudioMutation`. I'll add a sensor for this.

**Comment by rroller** [comment]
I've released 0.9.8, which adds more default events and an icon override for the AudioMutation event.

If you remove your cam and add it back, you should get this by default now. It looks like this...

![image](https://user-images.githubusercontent.com/445655/126077059-f604a65d-a9a1-4509-9704-97f8c4309822.png)

**Comment by rroller** [comment]
Resolving. Please reopen if you have any other issues.

**Comment by gzone156** [comment]
Sorry for lack of feedback, but I've been quite busy. Today i've tested the new implementation, and all works as expected. Many thanks for your effort!
