### ISSUE TITLE
Failed to handle message, error: 'NoneType' object has no attribute 'get', Line: 110

### ISSUE THREAD

**Issue by goncalorijo** [rroller/dahua#360]
I'm getting these errors, but everything seems to be working correctly.

![image](https://github.com/rroller/dahua/assets/64152617/de9aa8cc-9179-45e8-b75f-0515973fd658)

**Comment by rroller** [comment]
Thanks. Hard for me to tell what's going on from this screenshot. I'll see if I can put in some guard around nils where this error might originate from

**Comment by rroller** [comment]
speculative fix in https://github.com/rroller/dahua/releases/tag/0.9.58

**Comment by rroller** [comment]
Please reopen if you see this again

**Comment by goncalorijo** [comment]
Thank you for your reply and fix.

I've updated and restarted, but the erros keep showing up.

This error originated from a custom integration.

Logger: custom_components.dahua
Source: custom_components/dahua/vto.py:117
integration: Dahua (documentation, issues)
First occurred: 9:07:42 PM (41 occurrences)
Last logged: 10:31:05 PM

Failed to handle message, error: 'NoneType' object has no attribute 'get', Line: 113

![Screenshot_20240609-223139](https://github.com/rroller/dahua/assets/64152617/3a30e1f7-8169-46de-b56d-e86b0aa18c65)
