### ISSUE TITLE
Stuck on Version 0.5.0 ?

### ISSUE THREAD

**Issue by DReffects** [rroller/dahua#363]
The integration reports Verison 0.5.0 on in the device view:
![image](https://github.com/rroller/dahua/assets/48361672/7d51499e-b5f4-46ee-9dd6-ccd1004541e5)

I've just reinstalled the latest 0.9.58 release but no change. Is this a display bug or is something broken?

**Comment by glennodotcom** [comment]
I have the exact same issue.

**Comment by jbabio** [comment]
Exact same Issue here. The updates seem to be applied and the "updating from" version in the update window is newer than the 0.5.0 in the Device view.

**Comment by rroller** [comment]
Fixed in the latest release. This doesn't matter fwiw, but it is annoying to see the same version number. I'll fix keep it up2date going forward.
