### ISSUE TITLE
IVS Rule Details

### ISSUE THREAD

**Issue by ron-osu** [rroller/dahua#364]
Can you please add support to receive IVS details including the name of the custom IVS rule being triggered and the direction (leave vs enter) and object (human vs vehicle) detected?  The CrossRegionDetection sensor in HA is triggered when these IVS events occur, but I cannot see any of the specific IVS details.

![image](https://github.com/rroller/dahua/assets/79952004/6b3aa2ee-683c-40eb-8762-221d2c9e5e08)

I have been able to get this information into Home Assistant using a docker container (https://hub.docker.com/r/psyciknz/cameraevents) that publishes Dahua IVS event details via MQTT.  I believe this is the source code: https://github.com/psyciknz/CameraEvents.  This just provides a dynamic string but it can be parsed/searched to trigger automations.  There may be a better way to expose these details in HA but I'm a bit of a newbie to this platform.

![image](https://github.com/rroller/dahua/assets/79952004/f341a991-ef00-41c3-a49a-f5f1e7ff13b0)

Relavent configuration.yaml snippet for MQTT / CameraEvents:
mqtt:
  sensor:
    - name: "Camera IVS - Driveway"
      state_topic: "CameraEvents/IVS/Driveway"

It would be really nice to completely replace that docker container with this integration.  That seems to be the only gap in functionality between the two, at least for my use cases.

Either way, thank you so much for your efforts on this integration - it's working well for me!

**Comment by stalniy** [comment]
I configured it the way you want. It’s possible with https://github.com/rroller/dahua?tab=readme-ov-file#events

Don’t use sensors for IVS. They are useless for this task.

**Comment by ron-osu** [comment]
Thanks @stalniy - I wasn't aware of the events available in HA - this solves my ask completely!  This integration has been solid for me so far.
