### ISSUE TITLE
Smart Motion Events for Lorex E893ABP

### ISSUE THREAD

**Issue by Tom-Sumner** [rroller/dahua#371]
**Is your feature request related to a problem? Please describe.**
Can you take a look at the smart motion detection for Lorex E893ABP? I can toggle smart detection for humans and vehicles but can't get the actual events. I get the normal motion detection events just not smart ones.

**Describe the solution you'd like**
The ability to receive smart motion events for both Humans and Vehicles from my E893ABP model cameras.

**Describe alternatives you've considered**
I have looked through your code and done some reverse engineering of the camera already but to no avail.

Any help is appreciated!

**Comment by Tom-Sumner** [comment]
I have managed to get this working. I have also fixed the smart motion for human and vehicle toggles. Its janky but if you want the code just let me know.

**Comment by nobodyspecial** [comment]
I have the same issue with an Amcrest NVR.

**Comment by Tom-Sumner** [comment]
> I have the same issue with an Amcrest NVR.

I will set a reminder to post my very makeshift working code in about 15 hours from now. Please bear in mind that I may have broken the code for other devices. I built it using my own knowledge and reverse engineering of these cameras.

**Comment by Tom-Sumner** [comment]
> I have the same issue with an Amcrest NVR.

I have uploaded some code to my profile. This code fixes smart motion detection toggles and alerts for my cameras, as well as adding buttons to trigger the floodlight and the siren.
