### ISSUE TITLE
VTO2211G-WP as Generic RTSP device

### ISSUE THREAD

**Issue by thelittlechef** [rroller/dahua#412]
My VTO is now appearing as a generic RTSP device rather than a VTO. Not sure what changed other than the recent updates to this project and HA in the last week or so.

VTO2211G-WP
Firmware: 2021-11-16 V4.511.0000000.0.R

**Comment by man-jiteshm-sportsbet** [comment]
same has happened to me and i lost the bell_pressed sensor in HA

**Comment by man-jiteshm-sportsbet** [comment]
https://github.com/rroller/dahua/issues/417#issuecomment-2466593009

**Comment by thelittlechef** [comment]
How very odd - https was also turned on for my VTO. All back to normal once turned off again.

I don't remember changing that setting during the updates, but until proven otherwise, probably safe to assume I did!
