### ISSUE TITLE
Illuminator support for IPC-HFW2439SP-SA-LED-S2

### ISSUE THREAD

**Issue by adobrotvorskiy** [rroller/dahua#427]
Hi! Thanks a lot for integration! 
Is it possible to add Illuminator support for IPC-HFW2439SP-SA-LED-S2? 
For now for this camera integration provides IR which it actually hasn't and Illuminator is unavailable. 

I've tried API request for Ligthing_V2, and they work as described in integration:
[/cgi-bin/configManager.cgi?action=setConfig&Lighting_V2[0][0][0].Mode=Manual&Lighting_V2[0][0][0].MiddleLight[0].Light=39](url)
switches illuminator on

[/cgi-bin/configManager.cgi?action=setConfig&Lighting_V2[0][0][0].Mode=Off&Lighting_V2[0][0][0].MiddleLight[0].Light=39](url)
switches illuminator off

Also if in the `light.py` line 27 is commented
`    if coordinator.supports_illuminator(): `
switch for illuminator becomes available and it works. It switches illuminator on and off.  But for some reason when I switch it on it returns to off after little delay (illuminator still lights on until switch will be manually turned on and then off).

I will appreciate a lot if it can be resolved. Thanks in advance.

**Comment by adobrotvorskiy** [comment]
Managed to fix it. Added check for Lighing_V2 support and API call if it supported in __init__.py
After that all works for me.

Also edit check for infrared light support. IPC-HFW2439SP-SA-LED-S2 has no infrared light but it was found by integration.

**Comment by itplace** [comment]
hello @adobrotvorskiy are you able to provide steps in detail on how you fixed the issue. I have DH-IPC-HDW3849H-AS-PV-ANZ camera and illuminator is not working at all. Thanks heaps

**Comment by adobrotvorskiy** [comment]
@itplace hi! My solution was merged into main branch in 0.6.9 release. For now illuminator doesn't work due changes in HA 2025.1 update. 
In pull request code changes that fix it are posted. In some time it probably will be merged in new release
