### ISSUE TITLE
Add support for IVS

### ISSUE THREAD

**Issue by blademckain** [rroller/dahua#45]
Hi,
wanna u consider to add support for enabling/disabling IVS

```
def setIVS(ip=None, user=None, passw=None, enabled=True):
  enableRuleResponse = requests.get(
                        'http://'+ip+'/cgi-bin/configManager.cgi',
                        params={
                            'action': 'setConfig',
                            'VideoAnalyseRule[0][1].Enable': str(enabled).lower(),
                            'VideoAnalyseRule[0][2].Enable': str(enabled).lower(),
                            'VideoAnalyseRule[0][3].Enable': str(enabled).lower(),
                            'VideoAnalyseRule[0][4].Enable': str(enabled).lower(),
                            'VideoAnalyseRule[0][5].Enable': str(enabled).lower(),
                            },
                        auth=HTTPDigestAuth(user, passw),
                        )
  print('IPC response was:', enableRuleResponse.status_code)


def dahuaivs_enable(action=None, id=None, enable=True):
    """Enable/Disable IVS on Dahua Camera."""

    setIVS('192.168.12.42', username, password, enable)


```

**Comment by rroller** [comment]
Will do, thanks for the suggestion. I'll get to it ASAP.

**Comment by rroller** [comment]
I've added two services to support disable IVS rules. I didn't add a switch, do you need a switch too?
** `enable_all_ivs_rules` to disable or enable all IVS rules
** `enable_ivs_rule` to disable or enable a single IVS rule

<img width="1214" alt="Screen Shot 2021-07-05 at 12 02 15 PM" src="https://user-images.githubusercontent.com/445655/124510522-d85a0100-dd88-11eb-9e43-d1423169a454.png">

<img width="1216" alt="Screen Shot 2021-07-05 at 12 02 34 PM" src="https://user-images.githubusercontent.com/445655/124510545-e3ad2c80-dd88-11eb-9a92-8792c3e099bf.png">

**Comment by rroller** [comment]
Resolving. Please reopen if you have any issues.
