### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by luzik** [rroller/dahua#51]
My VTO2211G have option to turn https on. When it is checked all traffic from https:/IP:80/ is redirected to https://IP:443/.
SSL Certs are created on VTO itself so they are self signed. Please add support for such connection

**Comment by rroller** [comment]
Will do. I'll report back once I have this working.

**Comment by rroller** [comment]
0.9.4 is released and adds support for https with self signed certs.

NOTE: This assumes https is configured on port 443. If it turns out that others are using SSL on ports other than 443 then I'll add in an option. For now taking the easy road :) 

Please let me know if this works for you. Thanks!

**Comment by luzik** [comment]
Sorry not working after updating to 0.9.4
Logs says
Could not connect to Dahua device via the RPC2 API, falling back to cgi

**Comment by luzik** [comment]
I done it with removing and adding again VTO and changing port to 443

**Comment by rroller** [comment]
What camera model do you have?

**Comment by rroller** [comment]
Sorry just saw VTO2211G. I have a vto and will debug

**Comment by luzik** [comment]
Maybe I can help somehow ?
Redy to change code and turn some debug options

**Comment by rroller** [comment]
This is fixed in 0.9.5. I verified with my VTO.

Please try again and let me know how it goes. Thanks!

Also make sure when you add the integration you use port 443

**Comment by luzik** [comment]
It's working now
