### ISSUE TITLE
VTO call support (2 way communication)

### ISSUE THREAD

**Issue by luzik** [rroller/dahua#55]
It would be great to have roller/dahua support two way communication!

I believe this is great idea to HA take over VTH devices with roller/dahua

New VTO have already built in SIP maybe this plus what https://github.com/tommyjlong/doorvivint-card have under the hood will work ?

**Comment by rroller** [comment]
Great idea! I'll keep this open and work on it after I finish some of the other issues.

**Comment by lesykm** [comment]
Looks like AD410 implements bidirectional audio using ONVIF Profile T.
At least Amcrest View Pro Android app which works without any internet/cloud is able to implement bi-directional audio with AD410.
Not sure if this will help but may be decompilation of Amcrest View Pro can highlight of how does they implement it?

**Comment by mattkerrison** [comment]
Yea would love this to work as the ios app forces landscape when you answer currently.

New to ONVIF profiles but assume it has to be exposed somewhere as I noticed the DMSS app as well as Synology Surveillance Station can also do bi-directional audio.

I'd even settle for being able to fire off the 'quick reply' recordings that you can use in the amcrest app, but I haven't seen those anywhere either.

**Comment by conorlap** [comment]
For the Amcrest AD410, someone got 2-way audio and sending audio clip via the Tinycam app, all locally: https://www.reddit.com/r/BlueIris/comments/lpkt8z/achieved_local_doorbell_with_2_way_audio/

**Comment by conorlap** [comment]
Some progress being made on the [WebRTC](https://github.com/AlexxIT/WebRTC) card side. 

https://github.com/AlexxIT/WebRTC/issues/243#issuecomment-1193972484
The AD410 supports RTSP backchannel which may allow 2 way audio.

**Comment by AlexxIT** [comment]
Can you help me to find user **Dahua IPC-K42** or **IPC-K22**? I want to check if this models support RTSP backchannel before bye it for development purposes.

**Comment by luzik** [comment]
As SIP way is also some way to go, there is now a working solution using go2rtc. Please look at https://github.com/rroller/dahua/issues/181#issuecomment-1253233735
