### ISSUE TITLE
VTO door status is unreliable

### ISSUE THREAD

**Issue by luzik** [rroller/dahua#58]
Door status working fine only for 80% cases.
Sometimes door's are open but sensor status show its closed and the opposite.
Door status always changing with alarm_local, and this one seems to be 100% reliable, maybe there is problem with two messages concurrency or something ?

**Comment by rroller** [comment]
I don't have a unit connected to a door so I can't test this :/ 

The code just reads the event stream from the cam and fires events. You might look at the Home Assistant event bus to see if it fires the event you'd like to use...

https://github.com/rroller/dahua/blob/main/README.md#events
