### ISSUE TITLE
Support for Imou IPC-F22 Bullet 2C

### ISSUE THREAD

**Issue by noddy119** [rroller/dahua#64]
Hi.  Any chance of support for this camera?  I don't think it has http support on port 80. 

It can be configured by the Dahau Windows Config tool.  This also shows some cgi commands

**Comment by rroller** [comment]
Hi, please follow this thread https://github.com/rroller/dahua/issues/6

Once that thread is fixed then your cam would work. (NOTE: This isn't easy so its going to take time)
