### ISSUE TITLE
Request: Service for color/bw/auto

### ISSUE THREAD

**Issue by alekslyse** [rroller/dahua#65]
Dahua has issues with remembering the color profile (auto, bw, color) where it reset the settings. I see in the dahua API its an endpoint to change this - could it be implemented?

**Comment by rroller** [comment]
Can you point me to the API you saw? Or show me a screenshot of where you adjust this in the UI? Thanks!

**Comment by alekslyse** [comment]
> Can you point me to the API you saw? Or show me a screenshot of where you adjust this in the UI? Thanks!

Page 161 DayNightColor - api preference attached :)


[DAHUA_HTTP_API_V2.76 for ipcamtalk._com.pdf](https://github.com/rroller/dahua/files/6913076/DAHUA_HTTP_API_V2.76.for.ipcamtalk._com.pdf)

**Comment by alekslyse** [comment]
Picture reference 
<img width="503" alt="Screenshot 2021-08-01 at 19 20 15" src="https://user-images.githubusercontent.com/3678663/127779883-c7d5d5b7-3a32-4c20-8f6b-34e8c2dfb5ce.png">

I dont know if you have this implemented, but this is also things Dahua have issues with their firmware

1. Setting sub streams
2. Summer/winter time / correct date

**Comment by rroller** [comment]
I've added a HA service to do this. Released in 0.9.11. In a followup release I'll add a sensor to report the modes.
* `config_type`: general, day, night
* `mode`: Auto, Color, BlackWhite. Note Auto is also known as Brightness by Dahua

## With YAML
```yaml
service: dahua.set_video_in_day_night_mode
target:
  entity_id: camera.cam13_main
data:
  config_type: night
  mode: Color
```

## With the UI
<img width="1199" alt="Screen Shot 2021-08-01 at 12 42 28 PM" src="https://user-images.githubusercontent.com/445655/127783396-782d799c-5f51-4476-8690-cc0ad8d4f65a.png">

**Comment by rroller** [comment]
Please let me know if this resolves the feature request for you.

**Comment by alekslyse** [comment]
Thank you! Its working, but its throwing an error (working even if it throws the error)

`

Logger: homeassistant
Source: custom_components/dahua/dahua_utils.py:13
Integration: Dahua (documentation, issues)
First occurred: 22:24:33 (4 occurrences)
Last logged: 22:26:51
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 500, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 843, in state_attributes
    color_mode = self._light_internal_color_mode
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 695, in _light_internal_color_mode
    if COLOR_MODE_BRIGHTNESS in supported and self.brightness is not None:
  File "/config/custom_components/dahua/light.py", line 68, in brightness
    return self._coordinator.get_infrared_brightness()
  File "/config/custom_components/dahua/__init__.py", line 490, in get_infrared_brightness
    return dahua_utils.dahua_brightness_to_hass_brightness(bri)
  File "/config/custom_components/dahua/dahua_utils.py", line 13, in dahua_brightness_to_hass_brightness
    bri = int(bri_str)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

`

**Comment by rroller** [comment]
Thanks! This is now fixed in https://github.com/rroller/dahua/releases/tag/0.9.12

Can you confirm?

**Comment by alekslyse** [comment]
Yes I can confirm that it works now without an error.

I would suggest you make a service for

Time: Page 42
DST: Page 43
Enable / Disable / Config Sub Stream 1 and 2

**Comment by rroller** [comment]
Please open a new issue for those and I can add it.
