### ISSUE TITLE
Support request for XVR5104C-X device

### ISSUE THREAD

**Issue by mlunax** [rroller/dahua#68]
I would love to see support for XVR5104C-X Dahua device.
I was trying to use on v0.9.13 generic driver but not working.

I will try to read more about Dahua API but it isnt my priority now so I would like to see some advices about it.

Thank you in advance for any type of help.

**Comment by rroller** [comment]
I believe this will fall under https://github.com/rroller/dahua/issues/9

What happens when you try to add it? Anything in the logs?

**Comment by rroller** [comment]
For this please follow along in https://github.com/rroller/dahua/issues/9
