### ISSUE TITLE
Add support for Imou Ranger IQ privacy mode (hide the camera lens)

### ISSUE THREAD

**Issue by EmmanuelVella** [rroller/dahua#71]
Hello,

I have an Imou Ranger IQ (IPC-A26HI). Would it be possible to support the privacy mode (hide the camera lens, see https://www.imoulife.com/product/detail/RangerIQ) ?

It would be nice to have a switch to enable/disable privacy mode.

**Comment by rroller** [comment]
That can be done once those devices are supported (Which isn't easy).

I'm going to close this, please follow https://github.com/rroller/dahua/issues/6

**Comment by EmmanuelVella** [comment]
Ok thank you very much !
