### ISSUE TITLE
Only a single instance of a device is allowed.

### ISSUE THREAD

**Issue by piotr-jaromin** [rroller/dahua#72]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by piotr-jaromin** [comment]
1 of cameras is not aplicable, (Only a single instance of a device is allowed) whaqt can be wrong ?? Everything was working fine

**Comment by rroller** [comment]
I haven't seen this before. Can you give any more details? Or log files?

**Comment by piotr-jaromin** [comment]
Logger: custom_components.dahua
Source: custom_components/dahua/config_flow.py:198
Integration: Dahua (documentation, issues)
First occurred: 16:12:44 (1 occurrences)
Last logged: 16:12:44
Could not connect to Dahua device via the RPC2 API, falling back to cgi





Logger: custom_components.dahua
Source: custom_components/dahua/client.py:615
Integration: Dahua (documentation, issues)
First occurred: 16:12:45 (1 occurrences)
Last logged: 16:12:45
Could not connect to Dahua device

Traceback (most recent call last):
  File "/config/custom_components/dahua/config_flow.py", line 187, in _test_credentials
    await client.login()
  File "/config/custom_components/dahua/rpc2.py", line 100, in login
    return await self.request(method=method, params=params, url=url)
  File "/config/custom_components/dahua/rpc2.py", line 59, in request
    raise ConnectionError(str(resp))
ConnectionError: <ClientResponse(http://192.168.1.125:80/RPC2_Login) [200 OK]>
<CIMultiDictProxy('X-XSS-Protection': '1;mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "script-src 'self' 'unsafe-inline' 'unsafe-eval'", 'Strict-Transport-Security': 'max-age=604800; includeSubDomains', 'Connection': 'Keep-Alive', 'Set-Cookie': 'secure; HttpOnly', 'Content-Length': '182')>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dahua/config_flow.py", line 202, in _test_credentials
    data = await client2.get_machine_name()
  File "/config/custom_components/dahua/client.py", line 108, in get_machine_name
    return await self.get(url)
  File "/config/custom_components/dahua/client.py", line 629, in get
    raise exception
  File "/config/custom_components/dahua/client.py", line 615, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('http://192.168.1.125:80/cgi-bin/magicBox.cgi?action=getMachineName')

**Comment by peterp2001** [comment]
I have seen this message before, if you have a disabled your camera / doorbell entity and then tried to install the integration again. Could this be the case? Perhaps after trying to uninstall previously?

**Comment by rroller** [comment]
I think what @peterp2001 says is most likely the issue. Please reopen if this continues to be a problem.
