### ISSUE TITLE
Snapshot not created every time...connection keeps breaking IPC-HDW4231EM-ASE

### ISSUE THREAD

**Issue by Notrial** [rroller/dahua#73]
## Version of the custom_component
Using latest version

## Configuration

```yaml

Add your logs here.

```

## Describe the bug

I have IPC-HDW4231EM-ASE and for the most part, integration is working as it should.
Binary sensors seem to be working, switches as well and video stream works and loads pretty snappy.
The problem I have is with static images, and I think it has something to do with authorization.
Picture entity card with my camera entity shows every other sreenshot, so it loads (take a while) and then breaks, then loads the next one etc. What's weird is if I use the full stream on the card it works perfectly and loads fast.
When I try getting the snapshot, it only works about 50% of the time.
When I test the link with the token in the browser (https://xxx.duckdns.org/api/camera_proxy/camera.dahua_main?token=61c2ee0d83bcb4c36901a95ae7a297aeb49910d0bd4427e4bf04d7a40bd6a004) it works but then if I refresh after few seconds it shows "500: Internal Server Error"

When the snapshot doesn't work I get this in the log:
![image](https://user-images.githubusercontent.com/36201754/129869237-c1ccf353-21b5-419e-aac9-e1079f1d0c2a.png)

This is how the camera entity attributes look like:
![image](https://user-images.githubusercontent.com/36201754/129869370-decfa9b1-ecc7-4b75-8e18-39a77d1d3641.png)

Don't know if it's normal or not but in-camera log I see the constant log in/ log off from my hass client.

## Debug log

```text

Add your logs here.

```

**Comment by rroller** [comment]
I think that's just a function of these cameras. They are lower powered devices with buggy software. Some are better than others. You might try upgrading your cameras firmware (NOTE: That can brick it, do it at your own risk)

**Comment by Notrial** [comment]
OK, as long as it's not something in the component itself that's causing authorisation issues :)
