### ISSUE TITLE
Video delay

### ISSUE THREAD

**Issue by luzik** [rroller/dahua#74]
I got about ~10 seconds delay between real time and my tablet shows VTO live stream. Users suggesting switch to WebRTC, or just limit frame rate.

WebRTC works fine, didn't try others methods

**Comment by GaryOkie** [comment]
Adjusting a camera's frame rate can be easily done via the camera's web UI or other software (Surveillance Pro, IDMSS, NVR, etc.)

Not clear to me what the purpose would be to add this as an integration option.  In any case, if the objective is to greatly reduce the streaming lag, a frame rate adjustment tweak is probably not going to reduce it all that much.  

![image](https://user-images.githubusercontent.com/37629938/131257489-733ab621-b864-495a-b0db-af11635fff9f.png)

**Comment by rroller** [comment]
I looked into this some and I don't plan on adding this (FWIW, luzik is looking for the frame setting in HA not Dahua... there's two settings). It's better to not use HA as a way to view cams. Better to get dedicated software. It's just not going to work well and will require another option to wire through. If you want to use HA to view the cam it's better to use the webRTC addon.
