### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by pepe59** [rroller/dahua#8]
This error occurs about 3 times a day, but I do not know if it is important or does not mean anything.
The IPC-A26 camera operates normally
I modified the IP address in the protocol so that it is not readable.

This error comes from the integration itself

Logger: custom_components.dahua
Source: custom_components/dahua/client.py:461
Integration: Dahua (documentation, issues)
First occurred: 17:04:15 (1 occurrences)
Last logged: 17:04:15

TimeoutError fetching information from http://1xx.xxx.xx.62:80/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect&action=getConfig&name=Lighting[0][0] -

**Comment by rroller** [comment]
That's pretty normal. For various reasons the integration will timeout when calling the camera's APIs. Could be your network or just the cam in general. Thes cams are not high powered devices and sometimes will timeout.

**Comment by pepe59** [comment]
Thanks for explaining. I'm closing the problem
