### ISSUE TITLE
Dahua VTO2202F-P unable to stream video

### ISSUE THREAD

**Issue by peterp2001** [rroller/dahua#83]
I updated the firmware on the doorbell to 2021-08-12 V4.500.0000002.0.R and security baseline version 2.1 and reinstalled the Dahua integration and can no longer view video streams. I get a still picture that updates every now and again but no live video.

I can connect via VLC using the same rstp address with no issue.

The Home Assistant log file shows the following issues:

Logger: homeassistant.components.camera
Source: components/camera/__init__.py:465
Integration: Camera (documentation, issues)
First occurred: 15:59:02 (1 occurrences)
Last logged: 15:59:02

The camera entity camera.6f0c2a3paj801ec_main does not support requesting width and height, please open an issue with the integration author

Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:323
Integration: Stream (documentation, issues)
First occurred: 15:59:10 (1 occurrences)
Last logged: 15:59:10

Error opening stream rtsp://****:****@192.168.1.21:554/cam/realmonitor?channel=1&subtype=0

The camera entity camera.6f0c2a3paj801ec_main does not support requesting width and height, please open an issue with the integration author

**Comment by rroller** [comment]
I fixed the width and height issue in https://github.com/rroller/dahua/issues/84

Please upgrade to 0.9.23 and see if that helps. Thanks!

**Comment by peterp2001** [comment]
Hi, still no joy after upgrading

2021-09-13 17:55:45 ERROR (stream_worker) [libav.tcp] Failed to resolve hostname (it had my account username here so I assume it is related to the dahua issue): Try again
2021-09-13 17:55:45 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://****:****@192.168.1.21:554/cam/realmonitor?channel=1&subtype=0

**Comment by pepe59** [comment]
The IPC-A26 does not start and these errors are logged.
This probably happened after updating HA to version core-2021.9.6
```
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:323
Integration: Stream (documentation, issues)
First occurred: 22:10:45 (1 occurrences)
Last logged: 22:10:45

Error opening stream rtsp://****:****@172.16.1.163:554/cam/realmonitor?channel=0&subtype=0
```
```
Logger: libav.rtsp
Source: components/stream/worker.py:321
First occurred: 22:10:45 (1 occurrences)
Last logged: 22:10:45

method OPTIONS failed: 404 Not Found
```

**Comment by peterp2001** [comment]
> The IPC-A26 does not start and these errors are logged.
> This probably happened after updating HA to version core-2021.9.x
> 
> ```
> Logger: homeassistant.components.stream.worker
> Source: components/stream/worker.py:323
> Integration: Stream (documentation, issues)
> First occurred: 22:10:45 (1 occurrences)
> Last logged: 22:10:45
> 
> Error opening stream rtsp://****:****@172.16.1.163:554/cam/realmonitor?channel=0&subtype=0
> ```
> 
> ```
> Logger: libav.rtsp
> Source: components/stream/worker.py:321
> First occurred: 22:10:45 (1 occurrences)
> Last logged: 22:10:45
> 
> method OPTIONS failed: 404 Not Found
> ```

Most likely it was due to upgrade, hopefully there is a fix coming !

**Comment by rroller** [comment]
I'm on the same firmeware and baseline. Running the latest HA and dahua integration and things work. I'm using the webrtc plugin to stream the RTSP url provided by this (the dahua) integration.

I assume this is fixed now.
