### ISSUE TITLE
VTO abort call service

### ISSUE THREAD

**Issue by luzik** [rroller/dahua#87]
I'm always frustrated when I open the door after someone is calling, and the doorbell keeps ringing.

Maybe there is a way to abort call from VTO ? If yes - I will trigger it whenever doors are opened

**Comment by myhomeiot** [comment]
It's should be possible if integration allow you to send VTO command `console.runCmd` with param `{'command': 'hc'}`

Like it's done at [this integration](https://github.com/myhomeiot/DahuaVTO#some-command-examples) look to `Cancel VTO Call` example.

**Comment by rroller** [comment]
I'm sorry this took so long. I finally got some free time and implemented this and it is released in 0.9.32
https://github.com/rroller/dahua/releases/tag/0.9.32

Here's an example...

```yaml
service: dahua.vto_cancel_call
target:
  entity_id: camera.doorbell_main
```

**Comment by rroller** [comment]
Can you please test it out and let me know how it works for you?

**Comment by rroller** [comment]
Resolving now this is implemented. Please reopen if there's any issues.

**Comment by luzik** [comment]
It is working fine ! VTO stops ringing. Unfortunately my dahua DMSS app keeps ringing, don't know if it should stop too after call cancel, but it would be nice to change this behavior too. I do understand that this can be out of scope of this project.

**Comment by krzakx** [comment]
It doesn't work for me :( I do have VTO2311R-WP

<img width="1093" height="300" alt="Image" src="https://github.com/user-attachments/assets/8909cd02-a0ba-460f-958f-0f2f8c44078b" />

The way I've tested was simple, I did press button and just after sending out service using Home Assistant Developer Tools
