### ISSUE TITLE
IMOU CUE2 Support

### ISSUE THREAD

**Issue by goblinmaks** [rroller/dahua#88]
No support for IMOU CUE2 camera
![image](https://user-images.githubusercontent.com/1436234/133819683-c6aa5cbb-4095-4178-a13c-8bd89cdbac5f.png)

This is FR,

**Comment by goblinmaks** [comment]
Related to #6

**Comment by rroller** [comment]
Yes, please follow https://github.com/rroller/dahua/issues/6
