### ISSUE TITLE
Dahua DB11 Doorbell not able to connect

### ISSUE THREAD

**Issue by JSEHV** [rroller/dahua#93]
## Version of the custom_component
0.5.0 (as mentioned in the manifest file)

## Used Dahua Camera
Doorbell DHI-DB11 
https://dahuawiki.com/Doorbell/DB11

## Describe the bug
When trying to setup the DB11 Doorbell, the system can't accept the setup, as there is no port 80 (or no web interface at all) for this doorbell. There is an RTSP stream, you can login to the device with username and password. Also the Config Tool is able to configure the device as other Dahua camera's.

It would be nice if we are able to connect for the stream. Maybe even an event for a button push is possible.

## Possible option
Connect the doorbell without the web interface requirement.

**Comment by GaryOkie** [comment]
The DB11 has the same guts as the Amcrest AD110 doorbell which does connect.   Both lack a webUI, but both have a web server that respond to API calls over port 80 as well as RTSP.   

There is already the ability for this custom integration to pass events to Home Assistant.   This allows HASS to trigger on both pixel change motion (VideoMotion)  and doorbell button press (CallNoAnswered) events.
