### ISSUE TITLE
support for switch to enable smart motion detection

### ISSUE THREAD

**Issue by bintravel** [rroller/dahua#96]
Enable motion detection and enable smart motion detection are separate 'switches' in the config of the camera (in my case IPC-T5442T-ZE 4MP).
Enabling motion detection does not automatically enable smart motion detection, disabling motion detection automatically disables smart motion detection. Trough HA i can enable and disable the motion motion, but i can not re-enable the smart motion detection.

In my camera (IPC-T5442T-ZE 4MP) the smart motion detection covers detection of persons and vehicles. It is separate and different from the IVS possiblites.

Thanks for this great integration!

**Comment by tunip** [comment]
I have the same camera and the same missing function/switch.

Thanks for your work and this great integration.

**Comment by rroller** [comment]
This was added just now in 0.9.30 https://github.com/rroller/dahua/releases/tag/0.9.30

Please let me know if you have any issues.
